### ISSUE TITLE
Getting Map via Polyline

### ISSUE THREAD

**Issue by RichieMcMullen** [basvandorst/StravaPHP#14]
Having trouble displaying the map using the Polyline code retrieved from the activity object. Any ideas on how to display it (PHP or JS) ?

**Comment by qligier** [comment]
You can use the [Polyline Encoder](Polyline Encoder) library to decode the Polyline field. It returns the coordinates of each points.

**Comment by adriangibbons** [comment]
Hi @qligier, the URL in your post doesn't go anywhere. I think you mean [Polyline Encoder](https://github.com/dyaaj/polyline-encoder), which I have used and is excellent.

Btw, [PHP-Geometry](https://github.com/gregallensworth/PHP-Geometry) contains a nice implementation of the Ramer–Douglas–Peucker algorithm. This gives you a very similar looking line from far fewer points.

Instead of decoding the polyline into lat-lngs at the server side, you could do this in the browser if you use [Leaflet](https://github.com/Leaflet/Leaflet) maps through the [Leaflet.encoded](https://github.com/jieter/Leaflet.encoded) plugin :)

**Comment by adriangibbons** [comment]
@RichTT a couple of issues I have bumped into with encoded polylines:

1. If you pass the encoded polyline as part of browser URL, remember that you should [limit the overall URL length to 2,000 characters](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) - this can be an issue for encoded polylines that represent thousands of lat-lngs.

2. Escaping of special characters in encoded polylines. I've seen at least backslashes and have used PHP's [addslashes](http://php.net/manual/en/function.addslashes.php) and [stripslashes](http://php.net/manual/en/function.stripslashes.php).

**Comment by qligier** [comment]
Yes, sorry for the link. I only knew the older [google-map-polyline-encoding-tool](https://github.com/emcconville/google-map-polyline-encoding-tool) and I've changed it just before sending the message.
The Leaflet.encoded plugin seems a very good alternative.
